#!/usr/bin/env python

import os
import shutil

from config import Dirs, Disks, Files, Masks
from utils import xdm, checkFilesEq


### Main test

def runtest():
    """compare extracted files to reference files"""

    # compare with reference files generated by TI Image tool
    shutil.copyfile(Disks.recsdis, Disks.work)
    for fn in [
            "V1", "V16", "V126", "V127", "V128", "V254", "V10R",
            "V64V", "V255V1", "V255V2", "V255V3", "V255V4", "V255V5",
            # NOTE: F1.tfi has incorrect record count
            "F16", "F127", "F128", "F129", "F254", "F255", "F64V", "F10R"
            ]:
        xdm(Disks.work, "-e", fn, "-t", "-o", Files.output)
        checkFilesEq("TIFiles", Files.output,
                     os.path.join(Dirs.refs, fn + ".tfi"), "PROGRAM",
                     Masks.TIFile)

    # compare files extracted from fragmented image
    shutil.copyfile(Disks.frag, Disks.work)
    for fn in ["F1", "F6"]:
        xdm(Disks.work, "-e", fn, "-o", Files.output)
        checkFilesEq("Frag Disk", Files.output,
                     os.path.join(Dirs.refs, "FRAG" + fn), "DIS/VAR127")
    xdm(Disks.work, "-d", "F1")
    xdm(Disks.work, "-e", "F6", "-o", Files.output)
    checkFilesEq("Frag Disk", Files.output, os.path.join(Dirs.refs, "FRAGF6"),
                 "DIS/VAR127")
    shutil.copyfile(Disks.frag, Disks.work)
    xdm(Disks.work, "-a", Files.output, "-n", "COPY", "-f", "DIS/VAR127")
    xdm(Disks.work, "-e", "F1", "-o", Files.output)
    checkFilesEq("Frag Disk", Files.output, os.path.join(Dirs.refs, "FRAGF1"),
                 "DIS/VAR127")

    # cleanup
    os.remove(Files.output)
    os.remove(Disks.work)


if __name__ == "__main__":
    runtest()
