* autogenerated constants: errors

x0   equ  1

     li   r0, 1
!    movb b#42, r1

     cb   r4, b#>30
     socb b#48, r4
     jmp  -!

     mov  w#>aa01, @>af00
     xor  w#12345, r3

     movb b#'R', r1
     szc  w#'X', r3

     auto

     a    w#x0 + 2, r0         ; 3
     cb   r1, b#x0 * 2 + 5     ; 7
     socb b#4 - 2, @0
     c    r1, w#>7 * x0 / 2    ; 3

     data -1

     end
