* autogenerated constants

     aorg >a000

     li   r0, 1
!    movb @b_42, r1

     cb   r4, @b_48
     socb @b_48, r4
     jmp  -!

     mov  @w_haa01, @>af00
     xor  @w_12345, r3

     movb @b_R, r1
     szc  @w_X, r3

     a    @w_3, r0
     cb   r1, @b_7
     socb @b_2, @0
     c    r1, @w_3

b_2  byte 2
b_7  byte 7
b_42 byte 42
b_48 byte >30
b_R  byte >52
     byte 0  ; filler
w_3  data 3
w_X  data >0058
w_12345 data 12345
w_haa01 data >aa01

     data -1

     end
