* autogenerated constants

     rorg 

     li   r0, 1
     movb b#42, r1
     
     cb   r4, b#>30
     socb b#48, r4

     mov  w#>aa01, @>af00
     xor  w#12345, r3

     movb b#R, r1
     szc  w#X, r3

     data >ffff

     end
