* EXTERNAL SYMBOLS THAT ARE NOT RESOLVED BY ASSEMBLER

      REF VSBW,VMBW,VSBR,VMBR,VWTR,KSCAN

      DATA 1         * CANNOT HAVE REF AT ADDR 0!
      DATA VSBW
      DATA VSBR
      DATA VMBW
      DATA VMBR
      DATA VWTR
      DATA KSCAN

      END
