*  TEST IMAGE CREATION - EXPLICIT SLOAD

        IDT 'ASIMG3'

        DEF SFIRST,SLAST,SLOAD
        
        TEXT 'PRE IMAGE DATA'

SLOAD   AORG >B000
        NOP

        RORG
SFIRST  TEXT '**START IMAGE**'
        DATA SLOAD,SFIRST,SLAST
        TEXT '**END IMAGE**'

SLAST   TEXT 'POST IMAGE DATA'
        END
