*  TEST IMAGE CREATION - AORG

        IDT 'ASIMG2'

        DEF SFIRST,SLAST,SLOAD

        TEXT 'RORG TEXT'

        AORG >3800
        TEXT 'PRE IMAGE DATA'

SLOAD
SFIRST  TEXT '**START IMAGE**'
        DATA SLOAD,SFIRST,SLAST
        TEXT '**END IMAGE**'

SLAST   TEXT 'POST IMAGE DATA'
        END
