START:
 REM EXT; BASIC; SAMPLE
 CALL CLEAR :: CALL SCREEN(15)
LOOP:
 IF A>0 THEN A=1 ELSE GOTO LEND
INCR:
 A=A+1 :: GOSUB SUB1 :: GO TO DECR
LEND:
 GO SUB SUB1 :: GOTO LOOP
DECR:
 A=A-1 :: IF A=1 THEN INCR ELSE A=A+2 :: GOTO LOOP
SUB1:
 GO SUB SUB2 :: ON A GO TO LOOP,INCR,LEND
 RETURN
SUB2:
 A=A*2 :: RETURN
