 REM A VERSION OF NIM
 PRINT :"THERE ARE 21 COINS ON THE"
 PRINT "TABLE."
 PRINT "BY TURNS, EACH PLAYER TAKES"
 PRINT "1, 2 OR 3 COINS AWAY."
 PRINT "THE PLAYER WHO TAKES THE"
 PRINT "LAST COIN WINS.":
RESTART:
 N=21
TURN:
 PRINT "THERE ARE";N;"COINS LEFT"
HOWMANY:
 INPUT "TAKE HOW MANY (1-3)? ":M
 IF (M<1)+(M>3)THEN HOWMANY
 N=N-M
 PRINT "THERE ARE";N;"COINS LEFT"
 IF N=0 THEN YOUWIN
 M=N-INT(N/4)*4
 IF M<>0 THEN OKCHOICE
 M=1
OKCHOICE:
 N=N-M
 PRINT "I TAKE";M;"COINS"
 IF N=0 THEN IWIN
 GOTO TURN
YOUWIN:
 PRINT "CONGRATULATIONS, YOU WIN!"
 GOTO AGAIN
IWIN:
 PRINT "I WIN!"
AGAIN:
 INPUT "TRY AGAIN (Y/N) ":A$
 IF A$="Y" THEN RESTART
 PRINT "SEE YOU NEXT TIME"
 END
